---
# tasks file for create-ec2

    - name: Create an EC2 instance
      ec2:
        key_name: "{{ ssh_key }}"
        instance_type: "{{ instance_size }}"
        region: '{{ region }}'
        group_id: '{{ sec_group }}'
        image: '{{ ami }}'
        wait: true
        vpc_subnet_id: '{{ subnet }}'
        volumes:
           - device_name: /dev/sda1
             volume_type: "{{ vol_type }}"
             volume_size: "{{ vol_size_gb }}"
             delete_on_termination: true
        assign_public_ip: yes
      register: ec2



- name: Linux | Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 1
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
