---
# tasks file for create-ec2

    - name: Create an EC2 instance
      ec2:
        key_name: "{{ ssh_key }}"
        instance_type: "{{ instance_size }}"
        region: '{{ region }}'
        group_id: '{{ sec_group }}'
        image: '{{ ami }}'
        wait: true
        vpc_subnet_id: '{{ subnet }}'
        volumes:
           - device_name: /dev/sda1
             volume_type: "{{ vol_type }}"
             volume_size: "{{ vol_size_gb }}"
             delete_on_termination: true
        assign_public_ip: yes
      register: ec2_output



    - name: Wait for a while before confirming the server is ready
      vars:
        ansible_connection: local
      wait_for: 
        port: 22
        host: '{{ my_ec2_server.public_ip }}'
        delay: 30
      with_items: "{{ ec2_output.instances }}"
      loop_control:
        loop_var: my_ec2_server
